CREATE TABLE IF NOT EXISTS tb_pessoa (
  codigo INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(100) NOT NULL,
  cpf VARCHAR(14) NOT NULL,
  data_nascimento DATE NULL,
  sexo VARCHAR(12) NULL,
  PRIMARY KEY (codigo));